# Generated by Django 3.0.6 on 2020-06-17 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sent_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
