# Switch dockerfile
# for development: Dev.Dockerfile
# for production : Prod.Dockerfile

version: '3.7'

services:
    web:
        build: 
            context: ./frontend
            dockerfile: Docker/Dev.Dockerfile
        volumes:
        - ./frontend/:/usr/src/frontend/
        ports:
        - 4200:4200
        depends_on:
            - api

    api:
        build: 
            context: ./backend
            dockerfile: Docker/Dev.Dockerfile
        volumes:
        - ./backend/:/usr/src/backend/
        ports:
        - 8000:8000
        env_file:
        - ./env/.backend.env
        depends_on:
            - db
    
    db:
        image: postgres:12.0-alpine
        volumes:
        - postgres_data:/var/lib/postgresql/data/
        env_file:
            - ./env/.db.env
        
volumes:
    postgres_data: