version: 2.1

jobs:
  build:
    working_directory: ~/alumate/backend
    docker:
      - image: circleci/python:3.7
        environment:
          DEBUG: 1
          SECRET_KEY: g@z2g1)*of7u6ls1u%c3gddksqs4_603p!tn)t#tvqqe471h=9
          ALLOWED_HOSTS: localhost,127.0.0.1,0.0.0.0
          CORS_ORIGIN_WHITELIST: http://localhost:4200
    
    steps:
      - checkout:
          path: ~/alumate
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.7/site-packages"
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            python3 manage.py test
      - store_artifacts:
          path: .circleci/test-reports/
          destination: backend_app
